//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MOUSE_STATUS : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MOUSE_STATUS(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MOUSE_STATUS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MOUSE_STATUS() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          _cursesPINVOKE.delete_MOUSE_STATUS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      _cursesPINVOKE.MOUSE_STATUS_x_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MOUSE_STATUS_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      _cursesPINVOKE.MOUSE_STATUS_y_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MOUSE_STATUS_y_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_short button {
    set {
      _cursesPINVOKE.MOUSE_STATUS_button_set(swigCPtr, SWIGTYPE_p_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = _cursesPINVOKE.MOUSE_STATUS_button_get(swigCPtr);
      SWIGTYPE_p_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
      return ret;
    } 
  }

  public int changes {
    set {
      _cursesPINVOKE.MOUSE_STATUS_changes_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MOUSE_STATUS_changes_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_short xbutton {
    set {
      _cursesPINVOKE.MOUSE_STATUS_xbutton_set(swigCPtr, SWIGTYPE_p_short.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = _cursesPINVOKE.MOUSE_STATUS_xbutton_get(swigCPtr);
      SWIGTYPE_p_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
      return ret;
    } 
  }

  public MOUSE_STATUS() : this(_cursesPINVOKE.new_MOUSE_STATUS(), true) {
  }

}
