//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MEVENT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MEVENT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MEVENT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MEVENT() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          _cursesPINVOKE.delete_MEVENT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public short id {
    set {
      _cursesPINVOKE.MEVENT_id_set(swigCPtr, value);
    } 
    get {
      short ret = _cursesPINVOKE.MEVENT_id_get(swigCPtr);
      return ret;
    } 
  }

  public int x {
    set {
      _cursesPINVOKE.MEVENT_x_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MEVENT_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      _cursesPINVOKE.MEVENT_y_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MEVENT_y_get(swigCPtr);
      return ret;
    } 
  }

  public int z {
    set {
      _cursesPINVOKE.MEVENT_z_set(swigCPtr, value);
    } 
    get {
      int ret = _cursesPINVOKE.MEVENT_z_get(swigCPtr);
      return ret;
    } 
  }

  public uint bstate {
    set {
      _cursesPINVOKE.MEVENT_bstate_set(swigCPtr, value);
    } 
    get {
      uint ret = _cursesPINVOKE.MEVENT_bstate_get(swigCPtr);
      return ret;
    } 
  }

  public MEVENT() : this(_cursesPINVOKE.new_MEVENT(), true) {
  }

}
